### ISSUE TITLE
エラー時の実際のレスポンスとOASドキュメントの内容が違う

### ISSUE THREAD

**Issue by nimon-2AC** [kusumotolab/FL-online-demo#25]
間違ったドキュメントは，ドキュメントがないより悪いので修正するべき
思いつく修正方法は下の2つ
- 簡単な修正：エラー時のExampleやSchemaは載せないようにする
- 大変だけど嬉しい修正：エラー時のSchemaを実際のと合わせる

**Comment by hrtwt** [comment]
0a69173167d7b2b3f89b82d1d00c499402b9cfd4
一旦，前者で対応．
後者は別issueへ切り出し #26
